apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-hvs0
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-hvs0
    app.kubernetes.io/part-of: ci10t-777-0094-app
  name: devfile-sample-hvs0
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-hvs0
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-hvs0
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-777-0094-tenant/ci10t-777-0094-app/devfile-sample-hvs0@sha256:d294bd7f7e4b9549b76f5b3892579e5d37e52322ad3052d7adfd4c413a87c3d8
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
